name = "Up Business Theme"
license = "MIT"
licenselink = "https://github.com/jmeridth/up-business-theme/blob/main/LICENSE"
description = "A clean and modern landing page website inspired by clean and modern illustrations."

homepage = "https://github.com/jmeridth/up-business-theme/"
demosite = "https://jmeridth.gitlab.io/up-business-demo/"

tags = [
  "blog",
  "responsive",
  "personal",
  "light",
  "bootstrap",
  "portfolio",
  "landing",
  "company",
  "modern",
]
features = []

[author]
name = "Jason Meridth"
homepage = "https://jmeridth.com/"
